apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscontatoapipod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscontatoapipod
  template:
    metadata:
      labels:
        app: mscontatoapipod
    spec: 
      containers:
      - name: mscontatoapipod
        image: fabaofloripa/mscontatos.api:latest
        ports:
          - containerPort: 8084
  
---

apiVersion: v1
kind: Service
metadata:
  name: mscontatoapipod-service  
spec:
  selector:
    app: mscontatoapipod
  ports:
    - port: 8084
      port: 80      
  type: ClusterIP 
