# Deploy do postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrescontato
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: postgrescontato
  template:
    metadata:
      labels:
        app: postgrescontato
    spec:
      containers:
        - name: postgrescontato
          image: postgres:13.1
          env:
          - name: POSTGRES_PASSWORD
            value: Floripa102030
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: contatosdatabase
          ports:
            - containerPort: 5436
---
apiVersion: v1
kind: Service
metadata:
  name: postgrescontato
spec: 
  selector:
    app: postgrescontato
  ports:
    - targetPort: 5436
      port: 5432  
---
# Deploy da Aplicação Web

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscontatoapipod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscontatoapipod
  template:
    metadata:
      labels:
        app: mscontatoapipod
    spec: 
      containers:
      - name: mscontatoapipod
        image: fabaofloripa/mscontatos.api:latest
        env:
        - name: ConnectionStringPostgres
          value: "Host=postgrescontato;Database=contatosdatabase;Username=postgres;Password=Floripa102030"
        ports:
          - containerPort: 8084
  
---

apiVersion: v1
kind: Service
metadata:
  name: mscontatoapipod-service  
spec:
  selector:
    app: mscontatoapipod
  ports:
    - targetPort: 8084
      port: 80
