apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim
  labels:
    app: postgrescontato
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi